import React from 'react';
import './Landing.css';
import Image from 'react-bootstrap/Image'
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import Typewriter from 'typewriter-effect';

function Landing() {
    return(
        <>
            <div className="landingcontainer">
                <div className="mainText">
                    <h2>
                        Find research papers for
                    </h2>
                    <Typewriter
                            onInit={(typewriter1) => {
                                typewriter1
                                .typeString('<h1 style="color: #333232;">artificial intelligence</h1>')
                                .pauseFor(300)
                                .deleteAll(100)
                                .typeString('<h1 style="color: #333232;">climate change</h1>')
                                .pauseFor(300)
                                .deleteChars(14)
                                .typeString('<h1 style="color: #333232;">pandemics and viruses</h1>')
                                .pauseFor(150)
                                .deleteChars(21)
                                .typeString('<h1 style="color: #333232;">nanotechnology</h1>')
                                .pauseFor(75)
                                .deleteChars(14)
                                .typeString('<h1 style="color: #333232;">dark matter</h1>')
                                .pauseFor(37.5)
                                .deleteChars(11)
                                .typeString('<h1 style="color: #333232;">distributed computing</h1>')
                                .pauseFor(18.75)
                                .deleteChars(21)
                                .typeString('<h1 style="color: #333232; font-size: 50px; font-weight: bold;">you.</h1>')
                                .start();
                            }}
                        />
                        <a href="https://www.kas-tech.com/">Powered by <b>KASTech</b></a>
                        <div className="buttons">
                            <Button variant="dark" size="lg" href="/login" style={{fontFamily: "Inter",}}>Login</Button>{' '}
                            <Button variant="dark" size="lg" href="/register" style={{fontFamily: "Inter", marginLeft: "10%"}}>Register</Button>{' '}
                        </div>
                </div>
            </div>
            <div className="landingcontainer2">
                <h2>Our Mission</h2>
                <h1>Our mission is to make the world more <span class="bluebell">knowledgeable</span> through the easy access of <span class="vermillion">cutting-edge</span> research.</h1>
                <Button variant="outline-dark" size="lg" href="https://www.kas-tech.com/about" style={{fontFamily: "Inter", marginTop: "2%"}}>Meet the Team</Button>{' '}
            </div>

            <div className="landingcontainer3">
                <h2>Some Features</h2>
                <div className="rowppl">
                    <div className= "circles">
                        <Card style={{ width: "18rem", height: "19rem",marginRight: "5%", overflowY: "none", backgroundColor: "#171e24", display: "flex", textAlign: "center", borderRadius: "25px", boxShadow: "0 0 5px 5px lightgray"}}>
                            <Card.Body style={{alignItems: "center"}}>
                                <Card.Title style={{color: "#ecdfcf"}}>Get paid for publishing your paper!</Card.Title>
                                <Card.Text style={{color: "#ecdfcf"}}>We'll pay you 40% of all revenue generated by the number of clicks on your research paper.</Card.Text>
                            </Card.Body>
                        </Card>
                    </div>
                    <div className="circles">
                        <Card style={{ width: "25rem", height: "60%", overflowY: "none", backgroundColor: "#171e24", textAlign: "center", borderRadius: "25px", boxShadow: "0 0 5px 5px lightgray"}}>
                            <Card.Body style={{alignItems: "center"}}>
                                <Card.Title style={{color: "#ecdfcf"}}>Get access to quality research and upmark papers!</Card.Title>
                                <Card.Text style={{color: "#ecdfcf"}}>Find research papers tailored to your interests and upmark them. Research papers with more upmarks may make it onto the monthly journal issue for our paid subscribers. You'll get a 10% piece for making it on!</Card.Text>
                            </Card.Body>
                        </Card>
                        
                    </div>
                </div>
            </div>
        </>
    );
}


export default Landing;